import { expect, test, type APIRequestContext } from '@playwright/test'
import type { GenerationResponse } from '../../src/api/types'

test.skip(
  !process.env.PLAYWRIGHT_LIVE_BACKEND,
  'Set PLAYWRIGHT_LIVE_BACKEND=1 to run against the real backend stack.',
)

const CLASS_MODEL = `class Student {
  name;
  Integer id;
}

class Course {
  title;
}

association {
  * Student -- * Course;
}
`

const STRUCTURE_MODEL = `class PortedComponent {
  public in Integer input;
  public out Integer output;
}

class Composite {
  PortedComponent child;
}
`

async function postGenerate(
  request: APIRequestContext,
  baseURL: string,
  payload: Record<string, unknown>,
): Promise<GenerationResponse> {
  const response = await request.post(`${baseURL}/api/generate`, {
    data: payload,
  })

  expect(response.ok(), `POST /api/generate returned ${response.status()}`).toBeTruthy()
  return response.json()
}

test.describe('Live backend generation API', () => {
  test.setTimeout(120_000)

  test.beforeAll(async ({ request, baseURL }) => {
    const health = await request.get(`${baseURL}/api/health`)
    expect(health.ok()).toBeTruthy()
  })

  test('returns merged SVG diagram payloads for diagram targets', async ({
    request,
    baseURL,
  }) => {
    const response = await postGenerate(request, baseURL!, {
      code: CLASS_MODEL,
      diagramType: 'GvClassDiagram',
    })

    expect(response.svg).toContain('<svg')
    expect(response.result).toContain('Student')
    expect(response.generatedOutput).toBeUndefined()
    expect(response.generatedHtml).toBeUndefined()
    expect(response.generatedIframeUrl).toBeUndefined()
  })

  test('returns merged HTML diagram payloads for HTML-backed diagram targets', async ({
    request,
    baseURL,
  }) => {
    const response = await postGenerate(request, baseURL!, {
      code: STRUCTURE_MODEL,
      diagramType: 'StructureDiagram',
    })

    expect(response.html).toContain('<html')
    expect(response.generatedHtml).toBeUndefined()
    expect(response.generatedIframeUrl).toBeUndefined()
  })

  test('returns merged text generation payloads for code targets', async ({
    request,
    baseURL,
  }) => {
    const response = await postGenerate(request, baseURL!, {
      code: CLASS_MODEL,
      language: 'Java',
    })

    expect(response.generatedKind).toBe('text')
    expect(response.generatedLanguage).toBe('Java')
    expect(response.generatedOutput).toContain('class Student')
    expect(response.generatedHtml).toBeUndefined()
    expect(response.generatedIframeUrl).toBeUndefined()
  })

  test('returns merged generated HTML payloads for HTML generation targets', async ({
    request,
    baseURL,
  }) => {
    const response = await postGenerate(request, baseURL!, {
      code: CLASS_MODEL,
      language: 'SimpleMetrics',
    })

    expect(response.generatedKind).toBe('html')
    expect(response.generatedLanguage).toBe('SimpleMetrics')
    expect(response.generatedHtml).toContain('Metrics generated by Umple')
    expect(response.generatedOutput).toContain('Metrics generated by Umple')
    expect(response.generatedIframeUrl).toBeUndefined()
  })

  test('returns merged generated iframe payloads for iframe generation targets', async ({
    request,
    baseURL,
  }) => {
    const response = await postGenerate(request, baseURL!, {
      code: CLASS_MODEL,
      language: 'javadoc',
    })

    expect(response.generatedKind).toBe('iframe')
    expect(response.generatedLanguage).toBe('Java')
    expect(response.generatedIframeUrl).toContain('/api/generated/')
    expect(response.generatedDownloads?.length ?? 0).toBeGreaterThan(0)
    expect(response.generatedOutput).toContain('Javadoc generated')
    expect(response.generatedHtml).toBeUndefined()
  })
})
