package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/umple/umple-next/backend/internal/compiler"
	"github.com/umple/umple-next/backend/internal/config"
	"github.com/umple/umple-next/backend/internal/model"
)

type GenerateHandler struct {
	pool  *compiler.Pool
	store *model.Store
	cfg   *config.Config
}

func NewGenerateHandler(pool *compiler.Pool, store *model.Store, cfg *config.Config) *GenerateHandler {
	return &GenerateHandler{pool: pool, store: store, cfg: cfg}
}

type GenerateRequest struct {
	Code     string `json:"code"`
	Language string `json:"language"`
	ModelID  string `json:"modelId,omitempty"`
}

type GenerateResponse struct {
	Output   string `json:"output"`
	Language string `json:"language"`
	Errors   string `json:"errors,omitempty"`
	ModelID  string `json:"modelId"`
}

// validGenerateLanguages lists the languages supported by umple.jar -generate.
var validGenerateLanguages = map[string]bool{
	"Java":         true,
	"Php":          true,
	"Python":       true,
	"Ruby":         true,
	"Cpp":          true,
	"RTCpp":        true,
	"SimpleCpp":    true,
	"Json":         true,
	"Yuml":         true,
	"Ecore":        true,
	"Papyrus":      true,
	"TextUml":      true,
	"Umlet":        true,
	"USE":          true,
	"Sql":          true,
	"Alloy":        true,
	"NuSMV":        true,
	"SimulateJava": true,
}

func (h *GenerateHandler) Generate(w http.ResponseWriter, r *http.Request) {
	var req GenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}

	if req.Code == "" {
		writeError(w, http.StatusBadRequest, "code is required")
		return
	}
	if req.Language == "" {
		writeError(w, http.StatusBadRequest, "language is required")
		return
	}
	if !validGenerateLanguages[req.Language] {
		writeError(w, http.StatusBadRequest, fmt.Sprintf("unsupported language: %s", req.Language))
		return
	}

	// Ensure model directory exists
	modelID := req.ModelID
	if modelID == "" {
		m, err := h.store.Create(req.Code)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "failed to create model")
			return
		}
		modelID = m.ID
	} else {
		dir := h.store.ModelDir(modelID)
		if err := os.MkdirAll(dir, 0755); err != nil {
			writeError(w, http.StatusInternalServerError, "failed to create model dir")
			return
		}
		if err := os.WriteFile(filepath.Join(dir, "model.ump"), []byte(req.Code), 0644); err != nil {
			writeError(w, http.StatusInternalServerError, "failed to write model")
			return
		}
	}

	dir := h.store.ModelDir(modelID)
	command := fmt.Sprintf("-generate %s %s/model.ump", req.Language, dir)

	result, err := h.pool.Execute(compiler.CompileRequest{
		Command: command,
		WorkDir: dir,
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, fmt.Sprintf("generation failed: %v", err))
		return
	}

	// umple.jar writes generated files to disk rather than TCP output.
	// Read all generated files matching the language extension.
	output := result.Output
	if files, err := readGeneratedFiles(dir, req.Language); err == nil && files != "" {
		output = files
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(GenerateResponse{
		Output:   output,
		Language: req.Language,
		Errors:   result.Errors,
		ModelID:  modelID,
	})
}

// languageExtensions returns the file extensions generated by umple.jar for a language.
func languageExtensions(lang string) []string {
	switch lang {
	case "Java", "SimulateJava":
		return []string{".java"}
	case "Python":
		return []string{".py"}
	case "Php":
		return []string{".php"}
	case "Ruby":
		return []string{".rb"}
	case "Cpp", "RTCpp", "SimpleCpp":
		return []string{".cpp", ".h"}
	case "Json":
		return []string{".json"}
	case "Sql":
		return []string{".sql"}
	case "Alloy":
		return []string{".als"}
	case "NuSMV":
		return []string{".smv"}
	case "USE":
		return []string{".use"}
	case "Ecore":
		return []string{".ecore"}
	case "TextUml":
		return []string{".tuml"}
	case "Umlet":
		return []string{".uxf"}
	case "Yuml":
		return []string{".yuml"}
	case "Papyrus":
		return []string{".uml"}
	default:
		return nil
	}
}

// readGeneratedFiles reads all files in dir matching the language extensions
// and concatenates them with filename headers.
func readGeneratedFiles(dir, language string) (string, error) {
	exts := languageExtensions(language)
	if len(exts) == 0 {
		return "", fmt.Errorf("unknown language: %s", language)
	}

	extSet := make(map[string]bool, len(exts))
	for _, ext := range exts {
		extSet[ext] = true
	}

	var paths []string
	filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		if extSet[filepath.Ext(path)] && filepath.Base(path) != "model.ump" {
			paths = append(paths, path)
		}
		return nil
	})
	sort.Strings(paths)

	if len(paths) == 0 {
		return "", fmt.Errorf("no generated files found")
	}

	var parts []string
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		parts = append(parts, string(data))
	}

	return strings.Join(parts, "\n"), nil
}
