package gvparse

import (
	"regexp"
	"strings"
)

// ParseStateDiagram parses a GvStateDiagram .gv file and returns the state
// machines it contains. The .gv format is generated by umple.jar and has a
// predictable structure with comments, subgraph clusters, node definitions,
// and edge definitions.
func ParseStateDiagram(gvContent string) ([]StateMachine, error) {
	// Detect "no state machine" message
	if strings.Contains(gvContent, "No state machine found") {
		return nil, nil
	}

	lines := strings.Split(gvContent, "\n")

	// Pass 1: extract state machines, states, and start node IDs
	sms := extractStateMachines(lines)

	// Pass 2: extract transitions and attach to states
	transitions := extractTransitions(lines)
	attachTransitions(sms, transitions)

	// Pass 3: mark initial states from start transitions
	markInitialStates(sms, transitions)

	return sms, nil
}

// smContext tracks the current state machine being parsed.
type smContext struct {
	className string
	smName    string
	prefix    string // GV node prefix: "ClassName_smName"
}

func extractStateMachines(lines []string) []StateMachine {
	var sms []StateMachine
	smMap := make(map[string]int) // prefix -> index in sms

	var currentClass string
	var ctx *smContext

	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])

		// Track current class from comments
		if strings.HasPrefix(line, "// Class:") {
			currentClass = strings.TrimSpace(strings.TrimPrefix(line, "// Class:"))
			continue
		}

		// Detect SM boundary — either subgraph or comment-based
		if strings.HasPrefix(line, "// Top and Bottom Level StateMachine:") {
			smName := strings.TrimSpace(strings.TrimPrefix(line, "// Top and Bottom Level StateMachine:"))
			prefix := currentClass + "_" + smName
			if _, exists := smMap[prefix]; !exists {
				sms = append(sms, StateMachine{
					Name:      currentClass + "." + smName,
					ClassName: currentClass,
				})
				smMap[prefix] = len(sms) - 1
			}
			ctx = &smContext{className: currentClass, smName: smName, prefix: prefix}
			continue
		}

		// Subgraph with label overrides context
		if strings.HasPrefix(line, "subgraph cluster") {
			// Look for label on next lines
			for j := i + 1; j < len(lines) && j < i+5; j++ {
				labelLine := strings.TrimSpace(lines[j])
				if className, smName, ok := parseSubgraphLabel(labelLine); ok {
					prefix := className + "_" + smName
					if _, exists := smMap[prefix]; !exists {
						sms = append(sms, StateMachine{
							Name:      className + "." + smName,
							ClassName: className,
						})
						smMap[prefix] = len(sms) - 1
					}
					ctx = &smContext{className: className, smName: smName, prefix: prefix}
					break
				}
			}
			continue
		}

		// Parse state node definitions (collect multi-line attribute block)
		if ctx != nil && isStateNode(line, ctx.prefix) {
			attrBlock := collectAttrBlock(lines, i)
			state := parseStateNode(attrBlock, ctx.prefix)
			if state != nil {
				idx := smMap[ctx.prefix]
				sms[idx].States = append(sms[idx].States, *state)
			}
		}
	}

	return sms
}

// parseSubgraphLabel extracts className and smName from `label = "sm ClassName smName";`
func parseSubgraphLabel(line string) (string, string, bool) {
	if !strings.Contains(line, "label") {
		return "", "", false
	}

	// Extract the quoted value
	start := strings.Index(line, `"`)
	end := strings.LastIndex(line, `"`)
	if start == -1 || end <= start {
		return "", "", false
	}
	val := line[start+1 : end]

	// Expected format: "sm ClassName smName"
	if !strings.HasPrefix(val, "sm ") {
		return "", "", false
	}

	parts := strings.SplitN(val[3:], " ", 2)
	if len(parts) != 2 {
		return "", "", false
	}
	return parts[0], parts[1], true
}

// isStateNode checks if a line defines a regular state node (not a start node).
func isStateNode(line string, prefix string) bool {
	return strings.HasPrefix(line, prefix+"_") &&
		!strings.HasPrefix(line, "start_") &&
		strings.Contains(line, "[") &&
		strings.Contains(line, "label")
}

var stateNodeRe = regexp.MustCompile(`^\s*(\S+)\s*\[`)

// parseStateNode extracts a State from a GV node definition (may be multi-line).
func parseStateNode(line string, prefix string) *State {
	m := stateNodeRe.FindStringSubmatch(line)
	if m == nil {
		return nil
	}
	nodeID := m[1]

	// State name is the part after the prefix_
	stateName := strings.TrimPrefix(nodeID, prefix+"_")
	if stateName == "" {
		return nil
	}

	// Extract label (display name)
	label := extractAttr(line, "label")
	if label == "" {
		label = stateName
	}

	// Extract entry/exit actions from tooltip
	tooltip := extractAttr(line, "tooltip")
	entryActions, exitActions := parseTooltipActions(tooltip)

	return &State{
		Name:         stateName,
		EntryActions: entryActions,
		ExitActions:  exitActions,
		Transitions:  []Transition{},
		IsInitial:    false,
	}
}

// rawTransition holds a parsed edge before it's attached to a state machine.
type rawTransition struct {
	sourceID string
	targetID string
	event    string
	guard    string
	action   string
}

var edgeRe = regexp.MustCompile(`^\s*(\S+)\s*->\s*(\S+)\s*\[`)

func extractTransitions(lines []string) []rawTransition {
	var transitions []rawTransition

	for i := 0; i < len(lines); i++ {
		line := lines[i]
		m := edgeRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}

		sourceID := m[1]
		targetID := m[2]

		// Collect the full edge attribute block (may span multiple lines)
		attrBlock := collectAttrBlock(lines, i)

		label := extractAttr(attrBlock, "label")
		tooltip := extractAttr(attrBlock, "tooltip")

		event, guard, action := parseTransitionLabel(label)

		// If the label had a truncated action like "/ {...}", try the tooltip
		if action == "{...}" || action == "" {
			if tGuard, tAction := parseTransitionTooltip(tooltip); tAction != "" {
				action = tAction
			} else if guard == "" && tGuard != "" {
				guard = tGuard
			}
		}
		// Also get guard from tooltip if label didn't have one
		if guard == "" {
			tGuard, _ := parseTransitionTooltip(tooltip)
			if tGuard != "" {
				guard = tGuard
			}
		}

		transitions = append(transitions, rawTransition{
			sourceID: sourceID,
			targetID: targetID,
			event:    event,
			guard:    guard,
			action:   action,
		})
	}

	return transitions
}

// collectAttrBlock gathers the attribute string from a potentially multi-line edge/node definition.
func collectAttrBlock(lines []string, startLine int) string {
	var sb strings.Builder
	bracketDepth := 0
	for i := startLine; i < len(lines); i++ {
		sb.WriteString(lines[i])
		sb.WriteString("\n")
		bracketDepth += strings.Count(lines[i], "[") - strings.Count(lines[i], "]")
		if bracketDepth <= 0 && i > startLine {
			break
		}
		// Check if this single line has balanced brackets
		if i == startLine && bracketDepth <= 0 {
			break
		}
	}
	return sb.String()
}

func attachTransitions(sms []StateMachine, transitions []rawTransition) {
	for _, t := range transitions {
		// Skip start transitions (handled separately for marking initial states)
		if strings.HasPrefix(t.sourceID, "start_") {
			continue
		}

		// Find which SM and state this transition belongs to
		for smIdx := range sms {
			sm := &sms[smIdx]
			prefix := sm.ClassName + "_"
			// Check if source belongs to this SM's class
			if !strings.HasPrefix(t.sourceID, prefix) {
				continue
			}

			for stateIdx := range sm.States {
				expectedID := sm.ClassName + "_" + extractSmNameFromFull(sm.Name) + "_" + sm.States[stateIdx].Name
				if t.sourceID == expectedID {
					// Resolve target state name
					nextState := resolveTargetStateName(t.targetID, sm)
					sm.States[stateIdx].Transitions = append(sm.States[stateIdx].Transitions, Transition{
						Event:     t.event,
						Guard:     t.guard,
						Action:    t.action,
						NextState: nextState,
					})
					break
				}
			}
		}
	}
}

func markInitialStates(sms []StateMachine, transitions []rawTransition) {
	for _, t := range transitions {
		if !strings.HasPrefix(t.sourceID, "start_") {
			continue
		}

		// Find which SM this start belongs to
		for smIdx := range sms {
			sm := &sms[smIdx]
			smPrefix := sm.ClassName + "_" + extractSmNameFromFull(sm.Name)
			if t.sourceID == "start_"+smPrefix {
				// Find the target state
				targetName := resolveTargetStateName(t.targetID, sm)
				for stateIdx := range sm.States {
					if sm.States[stateIdx].Name == targetName {
						sm.States[stateIdx].IsInitial = true
						break
					}
				}
				break
			}
		}
	}
}

// extractSmNameFromFull extracts "smName" from "ClassName.smName".
func extractSmNameFromFull(fullName string) string {
	parts := strings.SplitN(fullName, ".", 2)
	if len(parts) == 2 {
		return parts[1]
	}
	return fullName
}

// resolveTargetStateName extracts the state name from a GV target node ID.
func resolveTargetStateName(targetID string, sm *StateMachine) string {
	prefix := sm.ClassName + "_" + extractSmNameFromFull(sm.Name) + "_"
	if strings.HasPrefix(targetID, prefix) {
		return strings.TrimPrefix(targetID, prefix)
	}
	// Fallback: last segment
	parts := strings.Split(targetID, "_")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return targetID
}

// extractAttr extracts a named attribute value from a GV attribute string.
// It handles both quoted and unquoted values.
func extractAttr(s string, name string) string {
	// Try patterns like: name = "value" or name = value,
	// We need to handle multi-line quoted strings with escaped quotes.

	// Find the attribute start
	patterns := []string{
		name + ` = "`,
		name + `="`,
		name + ` ="`,
	}

	for _, pat := range patterns {
		idx := strings.Index(s, pat)
		if idx == -1 {
			continue
		}

		// Skip the pattern to get to the value start
		valStart := idx + len(pat)

		// Find the closing quote, handling escaped quotes
		val := extractQuotedValue(s[valStart:])
		return decodeHTMLEntities(val)
	}

	// Try unquoted: name = value, or name = value]
	for _, sep := range []string{name + " = ", name + "="} {
		idx := strings.Index(s, sep)
		if idx == -1 {
			continue
		}
		valStart := idx + len(sep)
		rest := s[valStart:]
		// Value ends at comma, ], or newline
		endIdx := strings.IndexAny(rest, ",]\n")
		if endIdx == -1 {
			return strings.TrimSpace(rest)
		}
		return strings.TrimSpace(rest[:endIdx])
	}

	return ""
}

// extractQuotedValue extracts a value from a string starting after an opening quote.
func extractQuotedValue(s string) string {
	var sb strings.Builder
	escaped := false
	for i := 0; i < len(s); i++ {
		ch := s[i]
		if escaped {
			sb.WriteByte(ch)
			escaped = false
			continue
		}
		if ch == '\\' {
			escaped = true
			continue
		}
		if ch == '"' {
			return sb.String()
		}
		sb.WriteByte(ch)
	}
	return sb.String()
}

// parseTooltipActions extracts entry and exit actions from a state tooltip.
// Format: "Class X, SM y, State z&#13;Entry:\n  action1;\n  action2;&#13;Exit:\n  action3;"
func parseTooltipActions(tooltip string) (entry []string, exit []string) {
	if tooltip == "" {
		return nil, nil
	}

	// Split on the &#13; delimiter (already decoded or literal)
	// After HTML entity decoding, &#13; becomes \r
	sections := strings.Split(tooltip, "\r")
	if len(sections) == 1 {
		// Try with literal &#13; in case it wasn't decoded
		sections = strings.Split(tooltip, "&#13;")
	}

	for _, section := range sections[1:] { // skip the first section (state description)
		section = strings.TrimSpace(section)
		if strings.HasPrefix(section, "Entry:") {
			body := strings.TrimPrefix(section, "Entry:")
			entry = parseActionLines(body)
		} else if strings.HasPrefix(section, "Exit:") {
			body := strings.TrimPrefix(section, "Exit:")
			exit = parseActionLines(body)
		}
	}

	return entry, exit
}

// parseActionLines splits a multi-line action block into individual action strings.
func parseActionLines(body string) []string {
	var actions []string
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			actions = append(actions, line)
		}
	}
	return actions
}

// parseTransitionLabel parses "event [guard] / action" from a transition label.
func parseTransitionLabel(label string) (event, guard, action string) {
	if label == "" {
		return "", "", ""
	}

	s := label

	// Extract action: find last " / " (before optional {...})
	if slashIdx := strings.Index(s, " / "); slashIdx != -1 {
		action = strings.TrimSpace(s[slashIdx+3:])
		s = s[:slashIdx]
	}

	// Extract guard: find the outermost [...] pair
	if bracketStart := strings.Index(s, " ["); bracketStart != -1 {
		// Find matching close bracket from the end
		bracketEnd := strings.LastIndex(s, "]")
		if bracketEnd > bracketStart {
			guard = s[bracketStart+2 : bracketEnd]
			s = s[:bracketStart]
		}
	}

	event = strings.TrimSpace(s)
	return event, guard, action
}

// parseTransitionTooltip extracts guard and action from a transition tooltip.
// Format: "From X to Y on event&#13;Guard: [condition]&#13;Transition Action:\n  code;"
func parseTransitionTooltip(tooltip string) (guard, action string) {
	if tooltip == "" {
		return "", ""
	}

	// Split on &#13; or \r
	sections := strings.Split(tooltip, "\r")
	if len(sections) == 1 {
		sections = strings.Split(tooltip, "&#13;")
	}

	for _, section := range sections {
		section = strings.TrimSpace(section)
		if strings.HasPrefix(section, "Guard:") {
			g := strings.TrimSpace(strings.TrimPrefix(section, "Guard:"))
			// Strip outer brackets if present
			g = strings.TrimPrefix(g, "[")
			g = strings.TrimSuffix(g, "]")
			guard = strings.TrimSpace(g)
		} else if strings.HasPrefix(section, "Transition Action:") {
			body := strings.TrimPrefix(section, "Transition Action:")
			lines := parseActionLines(body)
			action = strings.Join(lines, "\n")
		}
	}

	return guard, action
}

// decodeHTMLEntities decodes common HTML entities found in GV tooltips.
func decodeHTMLEntities(s string) string {
	s = strings.ReplaceAll(s, "&#13;", "\r")
	s = strings.ReplaceAll(s, "&quot;", `"`)
	s = strings.ReplaceAll(s, "&amp;", "&")
	s = strings.ReplaceAll(s, "&lt;", "<")
	s = strings.ReplaceAll(s, "&gt;", ">")
	return s
}
