package gvparse

import (
	"testing"
)

// Simple Lamp example: single SM, no subgraph wrapper
const lampGV = `// Code generated by Umple 1.36.0.8088.f0fbd82bc

digraph "model" {
  compound = true;

  // Class: Lamp

    // Top and Bottom Level StateMachine: status

    // Start states are shown as a black circle
    node [ratio="auto" shape = point, fillcolor="black", width=0.2 ];
    start_Lamp_status [ tooltip = "Class Lamp, SM status, State start" ];


    // Format for normal states
    node [ratio="auto" shape = rectangle, width=1,style=rounded];

      // State: On

      Lamp_status_On [label = On, tooltip = "Class Lamp, SM status, State On", URL="javascript:Action.stateClicked(\"Lamp^*^status^*^On\")"];
      // End State: On

      // State: Off

      Lamp_status_Off [label = Off, tooltip = "Class Lamp, SM status, State Off", URL="javascript:Action.stateClicked(\"Lamp^*^status^*^Off\")"];
      // End State: Off
    // End Top and Bottom Level StateMachine: status

  // All transitions
    start_Lamp_status -> Lamp_status_On [  tooltip = "start to On", URL="javascript:Action.transitionClicked(\"null\")" ] ;
    Lamp_status_Off -> Lamp_status_On [  label = "turnOn", tooltip = "From Off to On on turnOn", URL="javascript:Action.transitionClicked(\"Lamp*^*status*^*turnOn*^*Off*^*On*^*\")" ] ;

  Lamp_status_On -> Lamp_status_Off [  label = "turnOff", tooltip = "From On to Off on turnOff", URL="javascript:Action.transitionClicked(\"Lamp*^*status*^*turnOff*^*On*^*Off*^*\")" ] ;


}`

// Multi-SM with subgraphs, entry/exit actions, guards, transition actions
const auctionGV = `// Code generated by Umple 1.36.0.8088.f0fbd82bc

digraph "model" {
  compound = true;

  // Class: Auction

    // Top and Bottom Level StateMachine: status

     subgraph clusterAuction_status {
      label = "sm Auction status";
      penwidth=0.5;

    // Start states are shown as a black circle
    node [ratio="auto" shape = point, fillcolor="black", width=0.2 ];
    start_Auction_status [ tooltip = "Class Auction, SM status, State start" ];


    // Format for normal states
    node [ratio="auto" shape = rectangle, width=1,style=rounded];

      // State: gathering

      Auction_status_gathering [label = gathering, tooltip = "Class Auction, SM status, State gathering", URL="javascript:Action.stateClicked(\"Auction^*^status^*^gathering\")"];
      // End State: gathering

      // State: underway

      Auction_status_underway [label = underway, tooltip = "Class Auction, SM status, State underway&#13;Exit:
   for(ItemAtAuction iau : getItemAtAuctions()) {
     iau.closeBids();
   }", URL="javascript:Action.stateClicked(\"Auction^*^status^*^underway\")"];
      // End State: underway

      // State: concluded

      Auction_status_concluded [label = concluded, tooltip = "Class Auction, SM status, State concluded", URL="javascript:Action.stateClicked(\"Auction^*^status^*^concluded\")"];
      // End State: concluded
    // End Top and Bottom Level StateMachine: status
  }

  // Class: ItemAtAuction

    // Top and Bottom Level StateMachine: status

     subgraph clusterItemAtAuction_status {
      label = "sm ItemAtAuction status";
      penwidth=0.5;

    // Start states are shown as a black circle
    node [ratio="auto" shape = point, fillcolor="black", width=0.2 ];
    start_ItemAtAuction_status [ tooltip = "Class ItemAtAuction, SM status, State start" ];


    // Format for normal states
    node [ratio="auto" shape = rectangle, width=1,style=rounded];

      // State: created

      ItemAtAuction_status_created [label = created, tooltip = "Class ItemAtAuction, SM status, State created", URL="javascript:Action.stateClicked(\"ItemAtAuction^*^status^*^created\")"];
      // End State: created

      // State: listed

      ItemAtAuction_status_listed [label = listed, tooltip = "Class ItemAtAuction, SM status, State listed&#13;Entry:
   highestBidPrice = reservePrice;", URL="javascript:Action.stateClicked(\"ItemAtAuction^*^status^*^listed\")"];
      // End State: listed

      // State: openForBidding

      ItemAtAuction_status_openForBidding [label = openForBidding, tooltip = "Class ItemAtAuction, SM status, State openForBidding", URL="javascript:Action.stateClicked(\"ItemAtAuction^*^status^*^openForBidding\")"];
      // End State: openForBidding

      // State: withdrawn

      ItemAtAuction_status_withdrawn [label = withdrawn, tooltip = "Class ItemAtAuction, SM status, State withdrawn&#13;Entry:
   active = false;", URL="javascript:Action.stateClicked(\"ItemAtAuction^*^status^*^withdrawn\")"];
      // End State: withdrawn

      // State: sold

      ItemAtAuction_status_sold [label = sold, tooltip = "Class ItemAtAuction, SM status, State sold&#13;Entry:
   active = false; sold=true;", URL="javascript:Action.stateClicked(\"ItemAtAuction^*^status^*^sold\")"];
      // End State: sold
    // End Top and Bottom Level StateMachine: status
  }

  // Class: Bid

  // Class: Person

  // Class: AuctionSimulation

  // All transitions
    start_Auction_status -> Auction_status_gathering [  tooltip = "start to gathering", URL="javascript:Action.transitionClicked(\"null\")" ] ;
    Auction_status_gathering -> Auction_status_underway [  label = "open", tooltip = "From gathering to underway on open", URL="javascript:Action.transitionClicked(\"Auction*^*status*^*open*^*gathering*^*underway*^*\")" ] ;

  Auction_status_underway -> Auction_status_concluded [  label = "close", tooltip = "From underway to concluded on close", URL="javascript:Action.transitionClicked(\"Auction*^*status*^*close*^*underway*^*concluded*^*\")" ] ;

  start_ItemAtAuction_status -> ItemAtAuction_status_created [  tooltip = "start to created", URL="javascript:Action.transitionClicked(\"null\")" ] ;
    ItemAtAuction_status_created -> ItemAtAuction_status_listed [  label = "listitem(double reserve) / {...}", tooltip = "From created to listed on listitem(double reserve)&#13;Transition Action:
     reservePrice = reserve;
     active = true;", URL="javascript:Action.transitionClicked(\"ItemAtAuction*^*status*^*listitem(double reserve)*^*created*^*listed*^*\")" ] ;

  ItemAtAuction_status_listed -> ItemAtAuction_status_openForBidding [  label = "openBidding [getAuction().getStatusFullName().equals(&quot;underway&quot;)]", tooltip = "From listed to openForBidding on openBidding&#13;Guard:  [getAuction().getStatusFullName().equals(&quot;underway&quot;)]", URL="javascript:Action.transitionClicked(\"ItemAtAuction*^*status*^*openBidding*^*listed*^*openForBidding*^* [getAuction().getStatusFullName().equals(&quot;underway&quot;)]\")" ] ;

  ItemAtAuction_status_openForBidding -> ItemAtAuction_status_openForBidding [  label = "bid(Bid newBid) [newBid.getBidValue() > highestBidPrice] / {...}", tooltip = "From openForBidding to openForBidding on bid(Bid newBid)&#13;Guard:  [newBid.getBidValue() > highestBidPrice]&#13;Transition Action:
     newBid.setAccepted(true);
     setHighestBidPrice(newBid.getBidValue());
     setHighestBidder(newBid.getBidder());", URL="javascript:Action.transitionClicked(\"ItemAtAuction*^*status*^*bid(Bid newBid)*^*openForBidding*^*openForBidding*^* [newBid.getBidValue() > highestBidPrice]\")" ] ;

  ItemAtAuction_status_listed -> ItemAtAuction_status_withdrawn [  label = "withdraw", tooltip = "From listed to withdrawn on withdraw", URL="javascript:Action.transitionClicked(\"ItemAtAuction*^*status*^*withdraw*^*listed*^*withdrawn*^*\")" ] ;

  ItemAtAuction_status_openForBidding -> ItemAtAuction_status_withdrawn [  label = "closeBids [highestBidPrice == reservePrice]", tooltip = "From openForBidding to withdrawn on closeBids&#13;Guard:  [highestBidPrice == reservePrice]", URL="javascript:Action.transitionClicked(\"ItemAtAuction*^*status*^*closeBids*^*openForBidding*^*withdrawn*^* [highestBidPrice == reservePrice]\")" ] ;

  ItemAtAuction_status_openForBidding -> ItemAtAuction_status_sold [  label = "closeBids [highestBidPrice > reservePrice] / {...}", tooltip = "From openForBidding to sold on closeBids&#13;Guard:  [highestBidPrice > reservePrice]&#13;Transition Action:
     setSalePrice(getHighestBidPrice());
     highestBidder.addItemsBought(this);", URL="javascript:Action.transitionClicked(\"ItemAtAuction*^*status*^*closeBids*^*openForBidding*^*sold*^* [highestBidPrice > reservePrice]\")" ] ;


}`

const noStateMachineGV = `// Code generated by Umple 1.36.0.8088.f0fbd82bc

digraph "model" {
  compound = true;
  node [ratio="auto" shape=box, penwidth=0];
  message [label ="No state machine found in the input Umple file"];

  // All transitions

}`

// Enum-like SMs: multiple SMs with only start transitions (no events)
const enumSMsGV = `// Code generated by Umple 1.36.0.8088.f0fbd82bc

digraph "model" {
  compound = true;

  // Class: FacilityType

    // Top and Bottom Level StateMachine: description

     subgraph clusterFacilityType_description {
      label = "sm FacilityType description";
      penwidth=0.5;

    // Start states are shown as a black circle
    node [ratio="auto" shape = point, fillcolor="black", width=0.2 ];
    start_FacilityType_description [ tooltip = "Class FacilityType, SM description, State start" ];


    // Format for normal states
    node [ratio="auto" shape = rectangle, width=1,style=rounded];

      // State: Menu

      FacilityType_description_Menu [label = Menu, tooltip = "Class FacilityType, SM description, State Menu", URL="javascript:Action.stateClicked(\"FacilityType^*^description^*^Menu\")"];
      // End State: Menu

      // State: Record

      FacilityType_description_Record [label = Record, tooltip = "Class FacilityType, SM description, State Record", URL="javascript:Action.stateClicked(\"FacilityType^*^description^*^Record\")"];
      // End State: Record

      // State: Screen

      FacilityType_description_Screen [label = Screen, tooltip = "Class FacilityType, SM description, State Screen", URL="javascript:Action.stateClicked(\"FacilityType^*^description^*^Screen\")"];
      // End State: Screen
    // End Top and Bottom Level StateMachine: description
  }

  // Class: Role

    // Top and Bottom Level StateMachine: role_description

     subgraph clusterRole_role_description {
      label = "sm Role role_description";
      penwidth=0.5;

    // Start states are shown as a black circle
    node [ratio="auto" shape = point, fillcolor="black", width=0.2 ];
    start_Role_role_description [ tooltip = "Class Role, SM role_description, State start" ];


    // Format for normal states
    node [ratio="auto" shape = rectangle, width=1,style=rounded];

      // State: Dba

      Role_role_description_Dba [label = Dba, tooltip = "Class Role, SM role_description, State Dba", URL="javascript:Action.stateClicked(\"Role^*^role_description^*^Dba\")"];
      // End State: Dba

      // State: ProjectMgr

      Role_role_description_ProjectMgr [label = ProjectMgr, tooltip = "Class Role, SM role_description, State ProjectMgr", URL="javascript:Action.stateClicked(\"Role^*^role_description^*^ProjectMgr\")"];
      // End State: ProjectMgr
    // End Top and Bottom Level StateMachine: role_description
  }

  // All transitions
    start_FacilityType_description -> FacilityType_description_Menu [  tooltip = "start to Menu", URL="javascript:Action.transitionClicked(\"null\")" ] ;
    start_Role_role_description -> Role_role_description_Dba [  tooltip = "start to Dba", URL="javascript:Action.transitionClicked(\"null\")" ] ;

}`

func TestParseLampSimple(t *testing.T) {
	sms, err := ParseStateDiagram(lampGV)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(sms) != 1 {
		t.Fatalf("expected 1 state machine, got %d", len(sms))
	}

	sm := sms[0]
	if sm.Name != "Lamp.status" {
		t.Errorf("expected name Lamp.status, got %s", sm.Name)
	}
	if sm.ClassName != "Lamp" {
		t.Errorf("expected className Lamp, got %s", sm.ClassName)
	}
	if len(sm.States) != 2 {
		t.Fatalf("expected 2 states, got %d", len(sm.States))
	}

	on := findState(sm.States, "On")
	off := findState(sm.States, "Off")
	if on == nil || off == nil {
		t.Fatal("expected states On and Off")
	}

	// On should be initial (start transition points to it)
	if !on.IsInitial {
		t.Error("expected On to be initial state")
	}
	if off.IsInitial {
		t.Error("expected Off to NOT be initial state")
	}

	// Check transitions
	if len(on.Transitions) != 1 {
		t.Fatalf("expected 1 transition from On, got %d", len(on.Transitions))
	}
	if on.Transitions[0].Event != "turnOff" || on.Transitions[0].NextState != "Off" {
		t.Errorf("unexpected transition from On: %+v", on.Transitions[0])
	}

	if len(off.Transitions) != 1 {
		t.Fatalf("expected 1 transition from Off, got %d", len(off.Transitions))
	}
	if off.Transitions[0].Event != "turnOn" || off.Transitions[0].NextState != "On" {
		t.Errorf("unexpected transition from Off: %+v", off.Transitions[0])
	}
}

func TestParseAuctionMultiSM(t *testing.T) {
	sms, err := ParseStateDiagram(auctionGV)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(sms) != 2 {
		t.Fatalf("expected 2 state machines, got %d", len(sms))
	}

	// Auction SM
	auction := findSM(sms, "Auction.status")
	if auction == nil {
		t.Fatal("expected Auction.status state machine")
	}
	if len(auction.States) != 3 {
		t.Fatalf("expected 3 states in Auction.status, got %d", len(auction.States))
	}

	gathering := findState(auction.States, "gathering")
	if gathering == nil {
		t.Fatal("expected gathering state")
	}
	if !gathering.IsInitial {
		t.Error("expected gathering to be initial")
	}
	if len(gathering.Transitions) != 1 || gathering.Transitions[0].Event != "open" {
		t.Errorf("expected open transition from gathering, got %+v", gathering.Transitions)
	}

	underway := findState(auction.States, "underway")
	if underway == nil {
		t.Fatal("expected underway state")
	}
	if len(underway.ExitActions) == 0 {
		t.Error("expected exit actions on underway state")
	}

	// ItemAtAuction SM
	item := findSM(sms, "ItemAtAuction.status")
	if item == nil {
		t.Fatal("expected ItemAtAuction.status state machine")
	}
	if len(item.States) != 5 {
		t.Fatalf("expected 5 states in ItemAtAuction.status, got %d", len(item.States))
	}

	// Check entry actions
	listed := findState(item.States, "listed")
	if listed == nil {
		t.Fatal("expected listed state")
	}
	if len(listed.EntryActions) == 0 {
		t.Error("expected entry actions on listed state")
	}

	// Check guard on transition
	if len(listed.Transitions) < 1 {
		t.Fatal("expected transitions from listed")
	}
	hasGuardTransition := false
	for _, tr := range listed.Transitions {
		if tr.Event == "openBidding" && tr.Guard != "" {
			hasGuardTransition = true
		}
	}
	if !hasGuardTransition {
		t.Error("expected openBidding transition with guard from listed")
	}

	// Check self-loop on openForBidding
	ofb := findState(item.States, "openForBidding")
	if ofb == nil {
		t.Fatal("expected openForBidding state")
	}
	hasSelfLoop := false
	for _, tr := range ofb.Transitions {
		if tr.NextState == "openForBidding" {
			hasSelfLoop = true
			if tr.Guard == "" {
				t.Error("expected guard on self-loop transition")
			}
			if tr.Action == "" {
				t.Error("expected action on self-loop transition")
			}
		}
	}
	if !hasSelfLoop {
		t.Error("expected self-loop transition on openForBidding")
	}

	// Check transition with action from tooltip
	created := findState(item.States, "created")
	if created == nil {
		t.Fatal("expected created state")
	}
	if len(created.Transitions) != 1 {
		t.Fatalf("expected 1 transition from created, got %d", len(created.Transitions))
	}
	if created.Transitions[0].Action == "" {
		t.Error("expected action on created->listed transition (from tooltip)")
	}
}

func TestParseNoStateMachine(t *testing.T) {
	sms, err := ParseStateDiagram(noStateMachineGV)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(sms) != 0 {
		t.Errorf("expected 0 state machines, got %d", len(sms))
	}
}

func TestParseEnumSMs(t *testing.T) {
	sms, err := ParseStateDiagram(enumSMsGV)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(sms) != 2 {
		t.Fatalf("expected 2 state machines, got %d", len(sms))
	}

	ft := findSM(sms, "FacilityType.description")
	if ft == nil {
		t.Fatal("expected FacilityType.description")
	}
	if len(ft.States) != 3 {
		t.Fatalf("expected 3 states, got %d", len(ft.States))
	}

	menu := findState(ft.States, "Menu")
	if menu == nil || !menu.IsInitial {
		t.Error("expected Menu to be initial state")
	}

	role := findSM(sms, "Role.role_description")
	if role == nil {
		t.Fatal("expected Role.role_description")
	}
	if len(role.States) != 2 {
		t.Fatalf("expected 2 states, got %d", len(role.States))
	}

	dba := findState(role.States, "Dba")
	if dba == nil || !dba.IsInitial {
		t.Error("expected Dba to be initial state")
	}
}

func TestParseTransitionLabel(t *testing.T) {
	tests := []struct {
		label   string
		event   string
		guard   string
		action  string
	}{
		{"turnOn", "turnOn", "", ""},
		{"open", "open", "", ""},
		{"listitem(double reserve) / {...}", "listitem(double reserve)", "", "{...}"},
		{"openBidding [condition]", "openBidding", "condition", ""},
		{"closeBids [x > y] / {...}", "closeBids", "x > y", "{...}"},
		{"bid(Bid b) [b.val > price] / {...}", "bid(Bid b)", "b.val > price", "{...}"},
	}

	for _, tt := range tests {
		event, guard, action := parseTransitionLabel(tt.label)
		if event != tt.event {
			t.Errorf("label=%q: event=%q, want %q", tt.label, event, tt.event)
		}
		if guard != tt.guard {
			t.Errorf("label=%q: guard=%q, want %q", tt.label, guard, tt.guard)
		}
		if action != tt.action {
			t.Errorf("label=%q: action=%q, want %q", tt.label, action, tt.action)
		}
	}
}

// helpers

func findSM(sms []StateMachine, name string) *StateMachine {
	for i := range sms {
		if sms[i].Name == name {
			return &sms[i]
		}
	}
	return nil
}

func findState(states []State, name string) *State {
	for i := range states {
		if states[i].Name == name {
			return &states[i]
		}
	}
	return nil
}
